/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematm;
import java.sql.*;

/**
 *
 * @author Fakhri
 */
public class MenuNasabah extends javax.swing.JFrame {
    private String norek;
    /**
     * Creates new form MenuATM
     */
    public MenuNasabah(String no_rek, String nama) {
        this.norek = no_rek;
        initComponents();
        jLabel1.setText("<html><center>SELAMAT DATANG DI ATM TEKNOFINANCE<br>(PECAHAN RP. 50.000)</center></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seratusRibu = new javax.swing.JButton();
        limaratusRibu = new javax.swing.JButton();
        bayarBeli = new javax.swing.JButton();
        eMoney = new javax.swing.JButton();
        tigaratusRibu = new javax.swing.JButton();
        satuJuta = new javax.swing.JButton();
        tarikManual = new javax.swing.JButton();
        transaksiLainnya = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seratusRibu.setText("100.000");
        seratusRibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seratusRibuActionPerformed(evt);
            }
        });

        limaratusRibu.setText("500.000");
        limaratusRibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaratusRibuActionPerformed(evt);
            }
        });

        bayarBeli.setText("BAYAR/BELI");

        eMoney.setText("UANG ELEKTRONIK");
        eMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMoneyActionPerformed(evt);
            }
        });

        tigaratusRibu.setText("300.000");
        tigaratusRibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaratusRibuActionPerformed(evt);
            }
        });

        satuJuta.setText("1.000.000");
        satuJuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuJutaActionPerformed(evt);
            }
        });

        tarikManual.setText("PENARIKAN JUMLAH LAIN");
        tarikManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikManualActionPerformed(evt);
            }
        });

        transaksiLainnya.setText("TRANSAKSI LAINNYA");
        transaksiLainnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiLainnyaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limaratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayarBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satuJuta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tigaratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarikManual, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksiLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tigaratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limaratusRibu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuJuta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayarBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarikManual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksiLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMoneyActionPerformed

    private void tigaratusRibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaratusRibuActionPerformed
        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = null;
        int saldoAkhir;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
            stmt = conn.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
            rs.next();
            if(Integer.parseInt(rs.getString(2))<300000){
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else {
                saldoAkhir = Integer.parseInt(rs.getString(2))-300000;
                rs.updateInt(2, saldoAkhir);
                rs.updateRow();
                javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.println("SQLException: " + e.getMessage());
            System.out.println("SQLState: " + e.getSQLState());
            System.out.println("VendorError: " + e.getErrorCode());
            javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        finally{
            if(rs != null){
                try {
                    rs.close();
                } catch (SQLException SQLEx){}

                stmt = null;
            }
        };
    }//GEN-LAST:event_tigaratusRibuActionPerformed

    private void satuJutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuJutaActionPerformed
        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = null;
        int saldoAkhir;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
            stmt = conn.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
            rs.next();
            if(Integer.parseInt(rs.getString(2))<1000000){
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else {
                saldoAkhir = Integer.parseInt(rs.getString(2))-1000000;
                rs.updateInt(2, saldoAkhir);
                rs.updateRow();
                javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.println("SQLException: " + e.getMessage());
            System.out.println("SQLState: " + e.getSQLState());
            System.out.println("VendorError: " + e.getErrorCode());
            javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        finally{
            if(rs != null){
                try {
                    rs.close();
                } catch (SQLException SQLEx){}

                stmt = null;
            }
        };
    }//GEN-LAST:event_satuJutaActionPerformed

    private void tarikManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikManualActionPerformed
        new TarikTunai(this.norek).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tarikManualActionPerformed

    private void transaksiLainnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiLainnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiLainnyaActionPerformed

    private void seratusRibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seratusRibuActionPerformed

        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = null;
        int saldoAkhir;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
            stmt = conn.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
            rs.next();
            if(Integer.parseInt(rs.getString(2))<100000){
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else {
                saldoAkhir = Integer.parseInt(rs.getString(2))-100000;
                rs.updateInt(2, saldoAkhir);
                rs.updateRow();
                javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.println("SQLException: " + e.getMessage());
            System.out.println("SQLState: " + e.getSQLState());
            System.out.println("VendorError: " + e.getErrorCode());
            javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        finally{
            if(rs != null){
                try {
                    rs.close();
                } catch (SQLException SQLEx){}

                stmt = null;
            }
        };
    }//GEN-LAST:event_seratusRibuActionPerformed

    private void limaratusRibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaratusRibuActionPerformed
        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = null;
        int saldoAkhir;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
            stmt = conn.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
            rs.next();
            if(Integer.parseInt(rs.getString(2))<500000){
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else {
                saldoAkhir = Integer.parseInt(rs.getString(2))-500000;
                rs.updateInt(2, saldoAkhir);
                rs.updateRow();
                javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.println("SQLException: " + e.getMessage());
            System.out.println("SQLState: " + e.getSQLState());
            System.out.println("VendorError: " + e.getErrorCode());
            javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        finally{
            if(rs != null){
                try {
                    rs.close();
                } catch (SQLException SQLEx){}

                stmt = null;
            }
        };
    }//GEN-LAST:event_limaratusRibuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuNasabah().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBeli;
    private javax.swing.JButton eMoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limaratusRibu;
    private javax.swing.JButton satuJuta;
    private javax.swing.JButton seratusRibu;
    private javax.swing.JButton tarikManual;
    private javax.swing.JButton tigaratusRibu;
    private javax.swing.JButton transaksiLainnya;
    // End of variables declaration//GEN-END:variables
}
