/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematm;
import java.sql.*;

/**
 *
 * @author Fakhri
 */
public class TarikTunai extends javax.swing.JFrame {
    private String norek;
    /**
     * Creates new form PenarikanManual
     */
    public TarikTunai(String no_rek) {
        this.norek = no_rek;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nominalTarikTunai = new javax.swing.JTextField();
        btnKonfirmasiTarikTunai = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Masukkan nominal yang anda inginkan");

        nominalTarikTunai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nominalTarikTunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nominalTarikTunaiKeyPressed(evt);
            }
        });

        btnKonfirmasiTarikTunai.setText("Konfirmasi");
        btnKonfirmasiTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiTarikTunaiActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(nominalTarikTunai)
                        .addComponent(btnKonfirmasiTarikTunai)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114)
                .addComponent(nominalTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnKonfirmasiTarikTunai)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiTarikTunaiActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(nominalTarikTunai.getText().trim())%50000 == 0){
            Statement stmt = null;
            ResultSet rs = null;
            Connection conn = null;
            int saldoAkhir;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
                stmt = conn.createStatement(
                        ResultSet.TYPE_SCROLL_INSENSITIVE,
                        ResultSet.CONCUR_UPDATABLE);
                rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
                rs.next();
                if(Integer.parseInt(rs.getString(2))<Integer.parseInt(nominalTarikTunai.getText().trim())){
                    javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                else {
                    saldoAkhir = Integer.parseInt(rs.getString(2))-Integer.parseInt(nominalTarikTunai.getText().trim());
                    rs.updateInt(2, saldoAkhir);
                    rs.updateRow();
                    javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    new MenuNasabah(this.norek, "").setVisible(true);
                    this.dispose();
                }
            }
            catch(SQLException e){
                System.out.println("SQLException: " + e.getMessage());
                System.out.println("SQLState: " + e.getSQLState());
                System.out.println("VendorError: " + e.getErrorCode());
                javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            finally{
                if(rs != null){
                    try {
                        rs.close();
                    } catch (SQLException SQLEx){}

                    stmt = null;
                }
            };
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Harus kelipatan Rp. 50.000,-", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKonfirmasiTarikTunaiActionPerformed

    private void nominalTarikTunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nominalTarikTunaiKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(Integer.parseInt(nominalTarikTunai.getText().trim())%50000 == 0){
                Statement stmt = null;
                ResultSet rs = null;
                Connection conn = null;
                int saldoAkhir;
                try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/sistem_atm?" + "user=root&password=");
                    stmt = conn.createStatement(
                            ResultSet.TYPE_SCROLL_INSENSITIVE,
                            ResultSet.CONCUR_UPDATABLE);
                    rs = stmt.executeQuery("SELECT * FROM saldo WHERE norek='"+norek+"'");
                    rs.next();
                    if(Integer.parseInt(rs.getString(2))<Integer.parseInt(nominalTarikTunai.getText().trim())){
                        javax.swing.JOptionPane.showMessageDialog(this, "Saldo anda tidak cukup.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                    else {
                        saldoAkhir = Integer.parseInt(rs.getString(2))-Integer.parseInt(nominalTarikTunai.getText().trim());
                        rs.updateInt(2, saldoAkhir);
                        rs.updateRow();
                        javax.swing.JOptionPane.showMessageDialog(this, "Transaksi anda sukses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        javax.swing.JOptionPane.showMessageDialog(this, "Sisa saldo anda: Rp. "+rs.getString(2)+",-", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        new MenuNasabah(this.norek, "").setVisible(true);
                        this.dispose();
                    }
                }
                catch(SQLException e){
                    System.out.println("SQLException: " + e.getMessage());
                    System.out.println("SQLState: " + e.getSQLState());
                    System.out.println("VendorError: " + e.getErrorCode());
                    javax.swing.JOptionPane.showMessageDialog(this, "Informasi login anda tidak valid.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                finally{
                    if(rs != null){
                        try {
                            rs.close();
                        } catch (SQLException SQLEx){}

                        stmt = null;
                    }
                };
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Harus kelipatan Rp. 50.000,-", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_nominalTarikTunaiKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuNasabah(this.norek, "").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TarikTunai().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasiTarikTunai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nominalTarikTunai;
    // End of variables declaration//GEN-END:variables
}
